### ISSUE TITLE
Уникальность полей по оси абсцисс

### ISSUE THREAD

**Issue by Znack** [artzub/minfin#1]
Привет!
Я пробую использовать твои наработки для создания аналогичного 3-х мерного графика, правда у меня будет немного другой смысл у данных и некоторые названия полей будут повторяться (от этого не уйти, к сожалению). Я к тому же уже ушел от входящих данных в формате csv, я сейчас данные с сервера напрямую в json читаю, сохраняя ту структуру данных, что уже была создана (иерархически вложенные объекты с ключами key и values). В итоге сейчас на вход я подаю сразу [нечто подобное](https://github.com/Znack/minfin/blob/master/data/data.json)
Так вот я пробовал продублировать самые верхние объекты (у которых ключи "I. Народное хозяйство", "II. Социально-культурные мероприятия", "II. Социально-культурные мероприятия" и тд), чтобы просто протестить, как отреагирует приложение на повторящиеся поля key у разных веток, и в итоге приложение просто проигнорировало все элементы, в которых повтороно поля key использовались.
Можно ли как-то от этого уйти? Что можно поправить, чтобы на заранее входящие json данные не было ограничения на уникальность поля key?

**Comment by artzub** [comment]
Я уже точно не помню, но чтобы не было дублей я делал какой то кастыль, по сути он как раз убирает дубли... где он не помню. посмотрю позже отпишусь.

**Comment by Znack** [comment]
В итоге я вернулся ко входным данным в csv, и научился делать эти уникальные ключи, как минумум для всех веток ниже первого уровня. По сути надо было просто по другому именовать tree_id, чтобы он не зависел от имени самого. Я сделал инкремент для каждого вызова restructure и более-менее заработало (есть еще там куча нюансов, но основная идея эта). Результат можно [тут посмотреть](https://github.com/Znack/minfin/commit/ae2c12b18dd5fd5a1eaae96e6658374ad74b2e32#diff-77ab163850ef0fa98d6a9ee9fb6bbcafR652)

**Comment by artzub** [comment]
Замечательно что заработало!!!!
